// Generated by CodiumAI

import { isJSON, parseJSON } from '@/common/utils/json'
import { describe, expect, it } from 'vitest'

describe('parseJSON', () => {
   // Should return null if argument is null
   it('should return null when argument is null', () => {
      const result = parseJSON(null)
      expect(result).toBeNull()
   })

   // Should return null if argument is empty string
   it('should return null when argument is empty string', () => {
      const result = parseJSON('')
      expect(result).toBeNull()
   })
})

describe('isJSON', () => {
   // Returns true when given a valid JSON string
   it('should return true when given a valid JSON string', () => {
      const arg = '{"name": "John", "age": 30}'
      const result = isJSON(arg)
      expect(result).toBe(true)
   })

   // Returns false when given a string that is only partially valid JSON
   it('should return false when given a string that is only partially valid JSON', () => {
      const arg = '{"name": "John", "age": 30,}'
      const result = isJSON(arg)
      expect(result).toBe(false)
   })
})
